### ISSUE TITLE
Incorrect labels at path endpoints

### ISSUE THREAD

**Issue by jlaufenb** [USFWS/collar-viewer#7]
Labels include "Last fix", but the value displayed for the starting point is the time stamp for second-to-last location used in plotting the path.  Recommend removing "Last fix" and replacing with "Fix time" and displaying the actual fix time for that point.  That way, users can clearly determine the beginning and end points for resident lynx moving about a local home range.  We could also use different icons for the end points.

**Comment by mccrea-cobb** [comment]
First and last fixes now have correct fix times. Added centered header to the map popup to indicate first or last fix. See 92b20a6a5c3d76f8148a6d05fb36c89bcf96dbb8.
